{spawn} = require 'child_process'
chokidar = require 'chokidar'
fs = require 'fs'

cmds = (optsToAddToJadeDefaultOpts=[], optsToAddToStylusDefaultOpts=[]) ->
    jopts = ['cv.jade', '-o', '../']
    optsToAddToJadeDefaultOpts.forEach (opt) -> if opt.length isnt 0 then jopts.push opt
    sopts = ['./styles/styles.styl', '-o', '../css']
    optsToAddToStylusDefaultOpts.forEach (opt) -> if opt.length isnt 0 then sopts.push opt
    spawn 'jade', jopts
    spawn 'stylus', sopts
    return

task 'prod', 'Compile for production!', ->
    console.log 'Doing your bidding....'
    cmd '', ['-c'] # Un-prettyfied jade and compressed stylus outputs

task 'dev', 'Compile for development!', ->
    console.log 'Here we go!'
    # init chokidar, we add folders later(to prevent chokidar from indexing its own src dir)
    # default of interval of 100 was too much for my pc to handle
    watcher = chokidar.watch('cv.jade', {interval: 500})
    cmds ['-p'] # Pretty readable html outputted
    watcher
        .add './styles'
        .add './includes'
        .on 'change', (path) ->
            console.log path
            cmds ['-p']
        .on 'add', (path) ->
            console.log path
            cmds ['-p']
